# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecordsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RecordsWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 130, 721, 421))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.GoogleSheetLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GoogleSheetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GoogleSheetLabel.setObjectName("GoogleSheetLabel")
        self.verticalLayout.addWidget(self.GoogleSheetLabel)
        self.sheetSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.sheetSelect.setEditable(True)
        self.sheetSelect.setObjectName("sheetSelect")
        self.sheetSelect.addItem("")
        self.sheetSelect.addItem("")
        self.sheetSelect.addItem("")
        self.verticalLayout.addWidget(self.sheetSelect)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.OrganizeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.OrganizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OrganizeLabel.setObjectName("OrganizeLabel")
        self.verticalLayout.addWidget(self.OrganizeLabel)
        self.organizeSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.organizeSelect.setEditable(False)
        self.organizeSelect.setObjectName("organizeSelect")
        self.organizeSelect.addItem("")
        self.organizeSelect.addItem("")
        self.verticalLayout.addWidget(self.organizeSelect)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.SearchRunnerLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.SearchRunnerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SearchRunnerLabel.setObjectName("SearchRunnerLabel")
        self.verticalLayout.addWidget(self.SearchRunnerLabel)
        self.runnerSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.runnerSelect.setObjectName("runnerSelect")
        self.verticalLayout.addWidget(self.runnerSelect)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setMaximumSize(QtCore.QSize(550, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.RecordsLabel = QtWidgets.QLabel(self.centralwidget)
        self.RecordsLabel.setGeometry(QtCore.QRect(30, 30, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.RecordsLabel.setFont(font)
        self.RecordsLabel.setObjectName("RecordsLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GoogleSheetLabel.setText(_translate("MainWindow", "GoogleSheet"))
        self.sheetSelect.setItemText(0, _translate("MainWindow", "Test"))
        self.sheetSelect.setItemText(1, _translate("MainWindow", "One"))
        self.sheetSelect.setItemText(2, _translate("MainWindow", "Two"))
        self.OrganizeLabel.setText(_translate("MainWindow", "Organize by:"))
        self.organizeSelect.setItemText(0, _translate("MainWindow", "Alphabet (A-Z)"))
        self.organizeSelect.setItemText(1, _translate("MainWindow", "Average Time"))
        self.SearchRunnerLabel.setText(_translate("MainWindow", "Search Runner"))
        self.RecordsLabel.setText(_translate("MainWindow", "Records"))
